### ISSUE TITLE
greek search

### ISSUE THREAD

**Issue by PietroLiuzzo** [EAGLE-BPN/Inscription-Search-Engine#28] opened 2016-02-29 10:18 UTC
Greek text search does not work.

**Comment by PietroLiuzzo** [comment] 2016-02-29 10:35
spec: from windows machine with IE does not work

**Comment by PietroLiuzzo** [comment] 2016-02-29 10:39
entering βασιλευς with greek keyboard I obtain 609.000+ results
comare with 24 results typing greek directly in.

**Comment by cprando** [comment] 2016-02-29 10:40
Please give us further details. I tried searching for "αυ" and it worked well.

**Comment by cprando** [comment] 2016-02-29 11:00
Tried with IE, Firefox, Chrome and I'm not able to replicate this problem. entering βασιλευς with greek keyboard I obtain 24 results, same as typing greek directly in.
Do you click on "Accept" after completing to enter the greek characters in the keyboard?

**Comment by PietroLiuzzo** [comment] 2016-02-29 11:15
yes, I clicked accept. the test here returned after ages the said 609.000+
results. it is not the first time we experience un-replicability of
results...

On 29 February 2016 at 11:00, cprando notifications@github.com wrote:

> Tried with IE, Firefox, Chrome and I'm not able to replicate this problem.
> entering βασιλευς with greek keyboard I obtain 24 results, same as typing
> greek directly in.
> Do you click on "Accept" after completing to enter the greek characters in
> the keyboard?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/EAGLE-BPN/Inscription-Search-Engine/issues/28#issuecomment-190154425
> .

## 

Pietro Maria Liuzzo
cel (EN): (+44)7529495584
Skype: pietro.liuzzo (Quingentole)
https://uk.linkedin.com/in/pietroliuzzo

**Comment by francescomambrini** [comment] 2016-02-29 11:25
I did some test with Pietro simultaneously and, by entering the string βασιλευς both with regular and virtual keyboard, I got 24 results (which sounds reasonable); I explored them and they look good (i.e. they were retrieved as expected). It's strange that the same behavior results in different numbers of hits...

**Comment by cprando** [comment] 2016-02-29 11:44
Funny thing... Pietro can you see the text βασιλευς appearing in the text field before clicking on Search?
Furthermore, are you sure you press Enter or click on the lens and you do not click on "Browse all"?

**Comment by PietroLiuzzo** [comment] 2016-02-29 12:59
I did accept than clicked the only visible button, browse all. it that is
wrong, than its deceiving. there should be a button to run the search and
not a browse all button. this explains probably also the other bug on the
browse all button it self

On 29 February 2016 at 11:44, cprando notifications@github.com wrote:

> Funny thing... Pietro can you see the text βασιλευς appearing in the text
> field before clicking on Search?
> Furthermore, are you sure you press Enter or click on the lens and you do
> not click on "Browse all"?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/EAGLE-BPN/Inscription-Search-Engine/issues/28#issuecomment-190173953
> .

## 

Pietro Maria Liuzzo
cel (EN): (+44)7529495584
Skype: pietro.liuzzo (Quingentole)
https://uk.linkedin.com/in/pietroliuzzo

**Comment by cprando** [comment] 2016-02-29 13:13
This explains everything!
The greek keyboard works well then, the problem is the meaning of the button "Browse all".
I close this issues and comment on issue 31

**Closed as completed by cprando** 2016-02-29 13:13 UTC
